server.port=${PORT:8080}

spring.datasource.url=jdbc:postgresql://simik_user:Am4fVHRWnYjGNoFbUWqihizcaI4uoQeK@dpg-d84d4brrjlhs73d5b4d0-a/simik
spring.datasource.username=simik_user
spring.datasource.password=Am4fVHRWnYjGNoFbUWqihizcaI4uoQeK

spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
